Api
johnie261/rails_react pull request #1
Opened 2023-07-12 15:02 UTC by johnie261

Hello there,
### I did the following:
- Created a new Rails app called 'hello-rails-react'.
- Created a table for storing your messages and creating 5 different greetings.
 - Created an API endpoint that selects a random greeting from the table.

2023-07-12 15:40 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @johnie261, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 15:40 UTC, Qoosim commented on app/javascript/App.js
> +export default App;
- [ ] I got below error message while trying to run you app for the fronend(react) home page.
- [ ] The same error message displayed when I ran your app for the backend(rails). But I used the `greetings/random_greeting` to check whether your app works as expected. It did. But you need to work on the root route to prevent error for the frontend(react). 

### Error frontend(react).
![react-error](https://github.com/johnie261/rails_react/assets/26597432/a470d383-fb3b-481b-987b-39b27c5cf687)

### Error backedn(rails)
![rails-error](https://github.com/johnie261/rails_react/assets/26597432/36f912b7-e3e6-4d1f-b01c-04c52f357adc)

2023-07-12 18:47 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @johnie261, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 18:47 UTC, bobb-Rob commented on app/javascript/greetingSlice.js
> +    const res = await fetch('http://127.0.0.1:3000/greetings/random_greeting');
- [ ] @Qoosim The students project was done properly, all you needed to do was change the API URL in the React app to your localhost like so 👇🏾 

```react
const res = await fetch('http://localhost:5000/greetings/random_greeting');
```

Please take incase you review this kind of project next time.

2023-07-12 19:01 UTC, merged

2023-07-13 10:02 UTC, Qoosim commented on app/javascript/greetingSlice.js
> +    const res = await fetch('http://127.0.0.1:3000/greetings/random_greeting');
> * [ ]  @Qoosim The students project was done properly, all you needed to do was change the API URL in the React app to your localhost like so 👇🏾
> 
> ```
> const res = await fetch('http://localhost:5000/greetings/random_greeting');
> ```
> 
> Please take incase you review this kind of project next time.

Oh, thanks.
Got it.